insert into ad2223_mdevos.Medicamentos (composicion) values ('Meclizine Hydrochloride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('OCTINOXATE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Camphor, Eucalyptus, Menthol');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Dandelion');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Methylergonovine Maleate');
insert into ad2223_mdevos.Medicamentos (composicion) values ('METFORMIN HYDROCHLORIDE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Lidocaine Hydrochloride, Bupivacaine Hydrochloride, Povidine Iodine');
insert into ad2223_mdevos.Medicamentos (composicion) values ('methimazole');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Oxycodone HCl and Acetaminophen');
insert into ad2223_mdevos.Medicamentos (composicion) values ('STANNOUS FLUORIDE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Sodium Fluoride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('OCTINOXATE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('ALUMINUM SULFATE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('METHYLPHENIDATE HYDROCHLORIDE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('mesalamine');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Moxifloxacin Hydrochloride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Acetaminophen and Diphenhydramine Hydrochloride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('hydrocortisone acetate pramoxine hcl');
insert into ad2223_mdevos.Medicamentos (composicion) values ('PYRITHIONE ZINC');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Morphine Sulfate');
insert into ad2223_mdevos.Medicamentos (composicion) values ('DOCUSATE SODIUM');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Anticoagulant Citrate Phosphate Dextrose (CPD) Solution and ADSOL Preservation Solution');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Triclosan');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Oxygen');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Levocarnitine');
insert into ad2223_mdevos.Medicamentos (composicion) values ('METOCLOPRAMIDE HYDROCHLORIDE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Hydroxyzine Hydrochloride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('HYDROCORTISONE ACETATE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('atenolol');
insert into ad2223_mdevos.Medicamentos (composicion) values ('METFORMIN HYDROCHLORIDE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Triclosan');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Acetaminophen and Codeine Phosphate');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Oxygen');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Hydrochlorothiazide');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Amlodipine Besylate');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Fluconazole');
insert into ad2223_mdevos.Medicamentos (composicion) values ('CALCIUM PHOSPHATE');
insert into ad2223_mdevos.Medicamentos (composicion) values ('atorvastatin calcium');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Galantamine');
insert into ad2223_mdevos.Medicamentos (composicion) values ('ALLANTOIN');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Loratadine');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Methocarbamol');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Dimenhydrinate');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Chlophedianol Hydrochloride, Guaifenesin, Phenylephrine Hydrochloride');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Hog Epithelia');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Lien Cichorium');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Berberis Oxalis');
insert into ad2223_mdevos.Medicamentos (composicion) values ('SODIUM PHOSPHATE, MONOBASIC, MONOHYDRATE, AND SODIUM PHOSPHATE, DIBASIC ANHYDROUS');
insert into ad2223_mdevos.Medicamentos (composicion) values ('ginkgo leaf extract');
insert into ad2223_mdevos.Medicamentos (composicion) values ('Melaleuca Pollen');
